# frpc配置 - 连接到独立FRP实例
serverAddr = "172.104.59.98"
serverPort = 7001  # 新的端口

# 认证配置 - 请替换为服务器生成的token
auth.method = "token"
auth.token = "storyboard_1754841832"

# 日志配置
log.to = "./frpc.log"
log.level = "info"

# Web服务配置
[[proxies]]
name = "storyboard-web"
type = "http"
localIP = "127.0.0.1"
localPort = 3000
customDomains = ["storyboard.172.104.59.98.nip.io"]
subdomain = "storyboard"

# TCP直连
[[proxies]]
name = "storyboard-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3000
remotePort = 4001