#!/bin/bash

# SSH连接到Linode服务器并设置FRP
SERVER_IP="172.104.59.98"

echo "======================================"
echo "连接到Linode服务器设置FRP"
echo "======================================"
echo ""
echo "服务器IP: $SERVER_IP"
echo ""
echo "请执行以下步骤："
echo ""
echo "1. SSH登录到服务器："
echo "   ssh root@$SERVER_IP"
echo ""
echo "2. 查看现有FRP配置："
echo "   cat /etc/frp/frps.ini"
echo "   或"
echo "   cat /opt/frp/frps.toml"
echo ""
echo "3. 找到token配置行："
echo "   auth.token = \"实际的token\""
echo "   或"
echo "   token = 实际的token"
echo ""
echo "4. 如果没有FRP，安装它："
echo "   curl -sSL https://raw.githubusercontent.com/dlkuajing/storyboard-ai-generator/main/deploy/server-install.sh | bash"
echo ""
echo "======================================"
echo ""
echo "获取到正确的token后，更新本地配置："
echo "1. 编辑 frpc.toml"
echo "2. 将 auth.token 改为服务器的实际token"
echo "3. 运行 ./frpc -c frpc.toml"
echo ""